<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use App\Helpers\GuidHelper;

class AddSubCategories extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('categories')->insert([
            [
                "name" => "Smart Phones",
                "description" => "Smart Phones",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 1,
            ],
            [
                "name" => "Accessories",
                "description" => "Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 1,
            ],
            [
                "name" => "Cars",
                "description" => "Cars",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 2,
            ],
            [
                "name" => "Car Parts",
                "description" => "Car Parts",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 2,
            ],
            [
                "name" => "Men Jewelry",
                "description" => "Men Jewelry",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 3,
            ],
            [
                "name" => "Women Jewelry",
                "description" => "Women Jewelry",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 3,
            ],
            [
                "name" => "Unisex",
                "description" => "Unisex",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 3,
            ],
            [
                "name" => "Men Clothes",
                "description" => "Men Clothes",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 4,
            ],
            [
                "name" => "Women Clothes",
                "description" => "Women Clothes",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 4,
            ],
            [
                "name" => "Kids Clothes",
                "description" => "Kids Clothes",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 4,
            ],
            [
                "name" => "All Electronics",
                "description" => "All Electronics",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 5,
            ],
            [
                "name" => "All Cultural Items",
                "description" => "All Cultural Items",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 6,
            ],
            [
                "name" => "Beverages",
                "description" => "Beverages",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 7,
            ],
            [
                "name" => "Fresh Products",
                "description" => "Fresh Products",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 7,
            ],
            [
                "name" => "Breakfast, Choco & Snacks",
                "description" => "Breakfast, Choco & Snacks",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 7,
            ],
            [
                "name" => "Food Staples",
                "description" => "Food Staples",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 7,
            ],
            [
                "name" => "Dairy & Chilled",
                "description" => "Dairy & Chilled",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 7,
            ],
            [
                "name" => "Laundry & Household",
                "description" => "Laundry & Household",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 7,
            ],
            [
                "name" => "Cat",
                "description" => "Cat",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 7,
            ],
            [
                "name" => "Dog",
                "description" => "Dog",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 7,
            ],
            [
                "name" => "Fish",
                "description" => "Fish",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 7,
            ],
            [
                "name" => "Frozen Food",
                "description" => "Frozen Food",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 7,
            ],
            [
                "name" => "Bath & Body",
                "description" => "Bath & Body",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 8,
            ],
            [
                "name" => "Beauty Tools",
                "description" => "Beauty Tools",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 8,
            ],
            [
                "name" => "Fragrances",
                "description" => "Fragrances",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 8,
            ],
            [
                "name" => "Hair Care",
                "description" => "Hair Care",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 8,
            ],
            [
                "name" => "Makeup",
                "description" => "Makeup",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 8,
            ],
            [
                "name" => "Men's Care",
                "description" => "Men's Care",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 8,
            ],
            [
                "name" => "Personal Care",
                "description" => "Personal Care",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 8,
            ],
            [
                "name" => "Skin Care",
                "description" => "Skin Care",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 8,
            ],
            [
                "name" => "Sexual Wellness",
                "description" => "Sexual Wellness",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 8,
            ],
            [
                "name" => "Medical Supplies",
                "description" => "Medical Supplies",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 8,
            ],
            [
                "name" => "T-Shirts & Tanks",
                "description" => "T-Shirts & Tanks",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 9,
            ],
            [
                "name" => "Shirts & Polo",
                "description" => "Shirts & Polo",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 9,
            ],
            [
                "name" => "Pants & Jeans",
                "description" => "Pants & Jeans",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 9,
            ],
            [
                "name" => "Shorts, Joggers & Sweats",
                "description" => "Shorts, Joggers & Sweats",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 9,
            ],
            [
                "name" => "Kurtas & Shalwar Kameez",
                "description" => "Kurtas & Shalwar Kameez",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 9,
            ],
            [
                "name" => "Winter Clothing",
                "description" => "Winter Clothing",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 9,
            ],
            [
                "name" => "Inner Wear",
                "description" => "Inner Wear",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 9,
            ],
            [
                "name" => "Shoes",
                "description" => "Shoes",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 9,
            ],
            [
                "name" => "Accessories",
                "description" => "Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 9,
            ],
            [
                "name" => "Boy's Clothing",
                "description" => "Boy's Clothing",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 9,
            ],
            [
                "name" => "Boy's Shoes",
                "description" => "Boy's Shoes",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 9,
            ],
            [
                "name" => "Boy's Accessories",
                "description" => "Boy's Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 9,
            ],
            [
                "name" => "Unstitched Fabric",
                "description" => "Unstitched Fabric",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 10,
            ],
            [
                "name" => "Kurtas & Shalwar Kameez",
                "description" => "Kurtas & Shalwar Kameez",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 10,
            ],
            [
                "name" => "Muslim Wear",
                "description" => "Muslim Wear",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 10,
            ],
            [
                "name" => "Tops",
                "description" => "Tops",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 10,
            ],
            [
                "name" => "Bras, Panties & Lingerie",
                "description" => "Bras, Panties & Lingerie",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 10,
            ],
            [
                "name" => "Sleepwear & Innerwear",
                "description" => "Sleepwear & Innerwear",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 10,
            ],
            [
                "name" => "Pants, Jeans & Leggings",
                "description" => "Pants, Jeans & Leggings",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 10,
            ],
            [
                "name" => "Dresses & Skirts",
                "description" => "Dresses & Skirts",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 10,
            ],
            [
                "name" => "Winter Clothing",
                "description" => "Winter Clothing",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 10,
            ],
            [
                "name" => "Shoes",
                "description" => "Shoes",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 10,
            ],
            [
                "name" => "Girls Clothing",
                "description" => "Girls Clothing",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 10,
            ],
            [
                "name" => "Girls Shoes",
                "description" => "Girls Shoes",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 10,
            ],
            [
                "name" => "Diapering & Potty",
                "description" => "Diapering & Potty",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Milk Formula & Baby",
                "description" => "Milk Formula & Baby",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Food",
                "description" => "Food",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Feeding",
                "description" => "Feeding",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Baby Gear",
                "description" => "Baby Gear",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Baby & Toddler Toys",
                "description" => "Baby & Toddler Toys",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Remote Control & Vehicles",
                "description" => "Remote Control & Vehicles",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Sports & Outdoor Play",
                "description" => "Sports & Outdoor Play",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Nursery",
                "description" => "Nursery",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Baby Personal Care",
                "description" => "Baby Personal Care",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Clothing & Accessories",
                "description" => "Clothing & Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Toys & Games",
                "description" => "Toys & Games",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Maternity Care",
                "description" => "Maternity Care",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 11,
            ],
            [
                "name" => "Bath",
                "description" => "Bath",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 12,
            ],
            [
                "name" => "Bedding",
                "description" => "Bedding",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 12,
            ],
            [
                "name" => "Decor",
                "description" => "Decor",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 12,
            ],
            [
                "name" => "Furniture",
                "description" => "Furniture",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 12,
            ],
            [
                "name" => "Kitchen & Dining",
                "description" => "Kitchen & Dining",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 12,
            ],
            [
                "name" => "Lighting",
                "description" => "Lighting",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 12,
            ],
            [
                "name" => "Laundry & Cleaning",
                "description" => "Laundry & Cleaning",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 12,
            ],
            [
                "name" => "Tools, DIY & Outdoor",
                "description" => "Tools, DIY & Outdoor",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 12,
            ],
            [
                "name" => "Stationery & Craft",
                "description" => "Stationery & Craft",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 12,
            ],
            [
                "name" => "Media, Music & Books",
                "description" => "Media, Music & Books",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 12,
            ],
            [
                "name" => "Mobile Accessories",
                "description" => "Mobile Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Headphones & Headsets",
                "description" => "Headphones & Headsets",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Wearable",
                "description" => "Wearable",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Camera Accessories",
                "description" => "Camera Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Computer Accessories",
                "description" => "Computer Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Storage",
                "description" => "Storage",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Printers",
                "description" => "Printers",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Ink & Toners",
                "description" => "Ink & Toners",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Fax Machines",
                "description" => "Fax Machines",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Computer Components",
                "description" => "Computer Components",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Portable Speakers",
                "description" => "Portable Speakers",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Network Components",
                "description" => "Network Components",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Gaming Accessories",
                "description" => "Gaming Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Monitors & Accessories",
                "description" => "Monitors & Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 13,
            ],
            [
                "name" => "Mobile Accessories",
                "description" => "Mobile Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 14,
            ],
            [
                "name" => "Headphones & Headsets",
                "description" => "Headphones & Headsets",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 14,
            ],
            [
                "name" => "Wearable",
                "description" => "Wearable",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 14,
            ],
            [
                "name" => "Camera Accessories",
                "description" => "Camera Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 14,
            ],
            [
                "name" => "Computer Accessories",
                "description" => "Computer Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 14,
            ],
            [
                "name" => "Storage",
                "description" => "Storage",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 14,
            ],
            [
                "name" => "Printers",
                "description" => "Printers",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 14,
            ],
            [
                "name" => "Computer Components",
                "description" => "Computer Components",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 14,
            ],
            [
                "name" => "Portable Speakers",
                "description" => "Portable Speakers",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 14,
            ],
            [
                "name" => "Network Components",
                "description" => "Network Components",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 14,
            ],
            [
                "name" => "Gaming Accessories",
                "description" => "Gaming Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 14,
            ],
            [
                "name" => "Monitors & Accessories",
                "description" => "Monitors & Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 14,
            ],
            [
                "name" => "Air Conditioner",
                "description" => "Air Conditioner",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 15,
            ],
            [
                "name" => "Televisions",
                "description" => "Televisions",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 15,
            ],
            [
                "name" => "Refrigerators & Freezers",
                "description" => "Refrigerators & Freezers",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 15,
            ],
            [
                "name" => "Home Audio & Theater",
                "description" => "Home Audio & Theater",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 15,
            ],
            [
                "name" => "Washing Machine",
                "description" => "Washing Machine",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 15,
            ],
            [
                "name" => "Kitchen Appliances",
                "description" => "Kitchen Appliances",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 15,
            ],
            [
                "name" => "Cooling & Heating",
                "description" => "Cooling & Heating",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 15,
            ],
            [
                "name" => "Irons & Garment Care",
                "description" => "Irons & Garment Care",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 15,
            ],
            [
                "name" => "Generator, UPS & Solar",
                "description" => "Generator, UPS & Solar",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 15,
            ],
            [
                "name" => "Projectors & Players",
                "description" => "Projectors & Players",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 15,
            ],
            [
                "name" => "TV Accessories",
                "description" => "TV Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 15,
            ],
            [
                "name" => "Vacuums & Floor Care",
                "description" => "Vacuums & Floor Care",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 15,
            ],
            [
                "name" => "Men's Watches",
                "description" => "Men's Watches",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 16,
            ],
            [
                "name" => "Women's Watches",
                "description" => "Women's Watches",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 16,
            ],
            [
                "name" => "Kid's Watches",
                "description" => "Kid's Watches",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 16,
            ],
            [
                "name" => "Womens Bags",
                "description" => "Womens Bags",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 16,
            ],
            [
                "name" => "Mens Bags",
                "description" => "Mens Bags",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 16,
            ],
            [
                "name" => "Luggage & Suitcase",
                "description" => "Luggage & Suitcase",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 16,
            ],
            [
                "name" => "Womens Jewellery",
                "description" => "Womens Jewellery",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 16,
            ],
            [
                "name" => "Mens Jewellery",
                "description" => "Mens Jewellery",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 16,
            ],
            [
                "name" => "Mens Accessories",
                "description" => "Mens Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 16,
            ],
            [
                "name" => "Women's Accessories",
                "description" => "Women's Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 16,
            ],
            [
                "name" => "Sunglasses & Eyewear",
                "description" => "Sunglasses & Eyewear",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 16,
            ],
            [
                "name" => "Exercise & Fitness",
                "description" => "Exercise & Fitness",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 17,
            ],
            [
                "name" => "Supplements",
                "description" => "Supplements",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 17,
            ],
            [
                "name" => "Shoes & Clothing",
                "description" => "Shoes & Clothing",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 17,
            ],
            [
                "name" => "Team Sports",
                "description" => "Team Sports",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 17,
            ],
            [
                "name" => "Rocket Soprts",
                "description" => "Rocket Soprts",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 17,
            ],
            [
                "name" => "Outdoor Recreation",
                "description" => "Outdoor Recreation",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 17,
            ],
            [
                "name" => "Fitness Gadgets",
                "description" => "Fitness Gadgets",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 17,
            ],
            [
                "name" => "Sports Accessories",
                "description" => "Sports Accessories",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 17,
            ],
            [
                "name" => "All Mix Items",
                "description" => "All Mix Items",
                "type" => "Product",
                "active" => true,
                "self_active" => true,
                "guid" => GuidHelper::getGuid(),
                "has_shipping" => true,
                "parent_id" => 18,
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
